### ISSUE TITLE
InconsistentVersionWarning Issue everytime I start wtp

### ISSUE THREAD

**Issue by TutubanaS** [segment-any-text/wtpsplit#105]
Hi, everytime I run a wtp object I get the following warning; 

```
InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info pl
ease refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
warnings.warn(
```
and ends. Any ideas on how to tackle this?

**Comment by bminixhofer** [comment]
Hey, you can either:
- manually install the recommended version of sklearn.
- ignore the warning. It should not have any impact.

I'll fix this when I have time but it's not really high prio since it shouldn't impact anything.

**Comment by markus583** [comment]
Not an issue with newer SaT models, so I close this issue.
