### ISSUE TITLE
Canine model and High VRAM usage

### ISSUE THREAD

**Issue by Qubitium** [segment-any-text/wtpsplit#115]
@bminixhofer  We are observing very high vram usage with canine model even though the `wtp-canine-s-12l-no-adapters` fp32 weights are only about 515MB so we naively expected batch=1 in fp16 mode to use 207.5MB of ram for weights plus runtime/inference costs. We didn't expect batch=1 vram to be 1.3GB. Input text is around 230kb text file. 

Is this a bug or architecture norm for the canine model? If norm, is there anything that we can do to reduce the memory footprint? Thanks. 

```
wtp = WtP("wtp-canine-s-12l-no-adapters")
wtp.half().to(device="cuda")
```

| batch |  vram GB   | 
|-------|---------|
| 1     |  1.309  |
| 2     |  1.335  | 
| 4     |  1.385  | 
| 6     |  1.428  | 
| 8     |  1.487  | 
| 10    |  1.542  | 
| 12    |  1.583  | 
| 14    |  1.639  | 
| 16    |  1.688  | 
| 32    |  2.094  |

**Comment by bminixhofer** [comment]
Hi, thanks for these benchmarks! And sorry for being slow to respond.

You could debug this by checking how much memory the vanilla CANINE (https://huggingface.co/google/canine-s) takes for a forward pass vs. a forward pass of the WtP model (see e.g. here: https://github.com/bminixhofer/wtpsplit/?tab=readme-ov-file#advanced-usage).

If there's a discrepancy there I'll investigate it. It's possible that CANINE just needs a lot of memory though, I am not super happy with that architecture and will have upgrade the models to a different arch soon(ish).

**Comment by bminixhofer** [comment]
Thanks! And that's very generous, deferring to @markus583 since he is doing the training but we are using TPUs so there is probably no need.

**Comment by markus583** [comment]
Very generous indeed! Thanks but the TPUs are very strong. I'd be very curious whether there is a discrepancy too.

**Comment by markus583** [comment]
Hi,

Could you check if this is still true for the newer SaT models?

**Comment by Qubitium** [comment]
@markus583  Confirmed using torch and v2.0.8 with `sat-3l-sm` model usage on 4090 is around `784MB`. This is at least 2x lower vram usage than older non-sat models.

**Comment by markus583** [comment]
Great! Many thanks for checking, this sounds very reasonable to me. If you still encounter memory issues, you could try `sat-1-sm`.
