### ISSUE TITLE
ImportError: cannot import name 'SaT' from 'wtpsplit' (/usr/local/lib/python3.10/site-packages/wtpsplit/__init__.py)

### ISSUE THREAD

**Issue by hwang136** [segment-any-text/wtpsplit#139]
after `pip install wtpsplit` I tried to 
`from wtpsplit import SaT`
but it shows 
ImportError: cannot import name 'SaT' from 'wtpsplit' (/usr/local/lib/python3.10/site-packages/wtpsplit/__init__.py)

**Comment by hwang136** [comment]
Also How can I load a local model using SaT it seems only support huggingface connection

**Comment by markus583** [comment]
Hi!
For the first issue related to importing, could you share your error message? I just tried again using a fresh install and it works just fine. Could you double-check your environment and installation?
You can simply load a local model by providing a directory with model files. See [this line here](https://github.com/segment-any-text/wtpsplit/blob/16f1a2c283a2f3145b1027c9bb9b8d910ca15f7e/wtpsplit/__init__.py#L449).

**Comment by hwang136** [comment]
simply boosting the version solved this problem. 
regarding to 2nd question.
I can provide a local model but not a local tokenizer whose path is hard coded so I create another segmenter class for this.

**Comment by markus583** [comment]
Great!
I see, that is not a current feature, indeed. Out of curiosity, why would you need such a feature? :)
