### ISSUE TITLE
2.1.1 treats \n as empty string

### ISSUE THREAD

**Issue by alexander-0000** [segment-any-text/wtpsplit#141]
Updating to 2.1.1 causes the behavior of treating '\n' as "".

**Comment by markus583** [comment]
It should not be an empty string, but a space (" "). This is intended and can be controlled with the _treat_newline_as_space_ flag. If you wish to restore the previous behavior, please set it to _True_.
See [here](https://github.com/segment-any-text/wtpsplit/blob/7e62ff2bba9fdb88abc1d0e4d8d801ccdb0d682d/wtpsplit/__init__.py#L798) for the implementation.

If you observe any different behavior, please let us know.
