### ISSUE TITLE
AssertionError on empty  input text

### ISSUE THREAD

**Issue by lifeiteng** [segment-any-text/wtpsplit#142]
```
from wtpsplit import SaT

sat = SaT("sat-3l")
# optionally run on GPU for better performance
# also supports TPUs via e.g. sat.to("xla:0"), in that case pass `pad_last_batch=True` to sat.split
sat.half().to("cuda")

[v for v in sat.split(["This is a test This is another test.", ""])]
```

```
wtpsplit/wtpsplit/extract.py", line 194, in extract
    assert current_chunk == num_chunks
AssertionError
```

**Comment by paulf-crypto** [comment]
Similar issue here. It can also happen when the text given as input is made of unkown tokens (ex: \r\n\r\n\r\n\r\n\r\n\r\n) which is then tokenized into an empty string and finally yield the same assertion error.

**Comment by markus583** [comment]
Hi, thanks for raising this. Both cases are now handled with the current version (2.1.2), which I just released. Please let me know if this fixes your issues.
