### ISSUE TITLE
No lookahead models

### ISSUE THREAD

**Issue by arinaruck** [segment-any-text/wtpsplit#143]
Hi!
Thank you for the great work!
I was wondering if it is possible to make the SaT models trained without lookahead models available (through huggingface).
As you point out, SaT models are more versatile that just sentence boundary detection and can be used for paragraph splitting as well (due to the '\n' prediction objective).
Based on the Table 9 for Appendix 1 in the SaT paper, it seems to me that limited lookahead nudges the models to perform more split (and more local) than the no-lookahead counterpart, leading to an improved performance on sentence boundary detection. 
However, this can potentially decrease the quality of paragraph splitting. 
I would love to test out this hypothesis and share my outcomes if you would be able to release the "no-lookahead" version.

Thank you!

**Comment by markus583** [comment]
Hi, they are available in our [huggingface organization](https://huggingface.co/segment-any-text), and, e.g., the model with 3 layers can be found [here](https://huggingface.co/segment-any-text/sat-3l-no-limited-lookahead).
Indeed, this could very well be the case! I also noticed that models with limited lookahead performed better at a slightly higher threshold (0.025 vs. 0.01 for models with limited lookahead).
So, I'd be curious to hear about your findings, and thanks for your interest in our project!

Best, Markus

**Comment by arinaruck** [comment]
Thank you for pointing this out! I was only checking the SaT Base Models collection.
