### ISSUE TITLE
How to load lora for SAT-SM

### ISSUE THREAD

**Issue by ifenghao** [segment-any-text/wtpsplit#145]
I was using following configs to train a LoRA for sat-12l-sm, but I found loading the LoRA by 
`sat_sm = SaT("sat-12l-sm", lora_path="sat-12l-sm-LL_lora/dataset/language_code")`, 
it prints "LoRA at sat-12l-sm-LL_lora/dataset/language_code not found, using base model...".
why should this happen?

> {
>     "model_name_or_path": "segment-any-text/sat-12l-sm",
>     "text_path": "dataset.pth",
>     "output_dir": "sat-12l-sm-LL_lora",
>     "shuffle": true,
>     "block_size": 256,
>     "eval_stride": 128,
>     "do_train": true,
>     "do_eval": true,
>     "per_device_train_batch_size": 64,
>     "per_device_eval_batch_size": 32,
>     "gradient_accumulation_steps": 1,
>     "eval_accumulation_steps": 8,
>     "dataloader_num_workers": 1,
>     "preprocessing_num_workers": 1,
>     "learning_rate": 1e-4,
>     "fp16": false,
>     "num_train_epochs": 30,
>     "logging_steps": 50,
>     "report_to": "wandb",
>     "wandb_project": "sentence",
>     "save_steps": 100000000,
>     "remove_unused_columns": false,
>     "one_sample_per_line": false,
>     "do_sentence_training": true,
>     "do_auxiliary_training": false,
>     "warmup_ratio": 0.1,
>     "non_punctuation_sample_ratio": null,
>     "prediction_loss_only": true,
>     "use_auxiliary": true,
>     "ddp_timeout": 3600,
>     "use_subwords": true,
>     "custom_punctuation_file": "punctuation_xlmr_unk.txt",
>     "log_level": "warning",
>     "adapter_config": "lora[r=16,alpha=32,intermediate_lora=True]",
>     "weight_decay": 0.0,
>     "auxiliary_remove_prob": 0.0,
>     "train_adapter": true,
>     "subsample": 10000
> }

the detailed error is as follows, seems like using unmatched LoRA configs when loading

> RuntimeError: Error(s) in loading state_dict for SubwordXLMForTokenClassification:
>         size mismatch for classifier.weight: copying a param with shape torch.Size([111, 768]) from checkpoint, the shape in current model is torch.Size
> ([1, 768]).
>         size mismatch for classifier.bias: copying a param with shape torch.Size([111]) from checkpoint, the shape in current model is torch.Size([1]).

**Comment by markus583** [comment]
Hi! We did not release LoRA weights for -SM models as we observed that SaT-SM+LoRA did make any difference compared to SaT+LoRA. So there are only LoRA-weights for non-SM models.
So you have 2 choices now:

1. Use SaT+LoRA (choose from, e.g., here: [SaT-3l-LoRAs](https://huggingface.co/segment-any-text/sat-3l/tree/main/loras)). This will yield the best results for a specific language and sentence style.
2. Use SaT-SM, no LoRA, with the benefit of not having to specify any language code or style.

Let me know if this works for you :)

**Comment by ifenghao** [comment]
> Hi! We did not release LoRA weights for -SM models as we observed that SaT-SM+LoRA did make any difference compared to SaT+LoRA. So there are only LoRA-weights for non-SM models. So you have 2 choices now:
> 
> 1. Use SaT+LoRA (choose from, e.g., here: [SaT-3l-LoRAs](https://huggingface.co/segment-any-text/sat-3l/tree/main/loras)). This will yield the best results for a specific language and sentence style.
> 2. Use SaT-SM, no LoRA, with the benefit of not having to specify any language code or style.
> 
> Let me know if this works for you :)

much thanks! 
In my scenario I found -SM models already work remarkably better than any vanilla SaT or SaT+LoRA models, but there are still a few bad cases left to be resolved, maybe finetuning on -SM models should be a much easier resolution, which I was trying to find.

**Comment by markus583** [comment]
Hi, I found some weights on my hard drive and uploaded them here for the 3L/12L non-SM models (each with limited lookahead, as described in the paper) here:
[Drive Link](https://drive.google.com/drive/folders/1ypT9QqcVEe61_JGg5csA3rVujSMZIpCp?usp=drive_link)
